### ISSUE TITLE
Pubsub subscription blocking + ref counting

### ISSUE THREAD

**Issue by aratz-lasa** [wetware/ww#52]
Two issues/bugs are detected in Wetware:

# Pubsub subscription blocking
Sometimes when a client connects to a wetware server and iterates over a subscription the client does not exit the loop. Instead, it gets blocked forever.

# Topic reference counting
Sometimes if you connect a client to a wetware server and you try to subscribe to a topic, you receive back `pubsub.capnp:Topic.subscribe: topic already exists`, which indicates an issue related to internal reference counting of topics. Currently, we have no info to reproduce this bug.

**Comment by lthibault** [comment]
This appears to happen across incompatible versions of Wetware.  Closing (hopefully for good!)
