### ISSUE TITLE
RPC metrics are not being sent

### ISSUE THREAD

**Issue by aratz-lasa** [wetware/ww#53]
Currently, ww has in place logic for sending metrics to Datadog-like platforms. However, these metrics are missing in the latest ww version. For example, we do not receive anymore the amount of rpc opened connections that casm exposes: [https://github.com/wetware/casm/blob/2efcedf8543c667fccf2b7aafdb02dfad778cc1e/pkg/vat.go#L176](https://github.com/wetware/casm/blob/2efcedf8543c667fccf2b7aafdb02dfad778cc1e/pkg/vat.go#L176)

**Comment by lthibault** [comment]
Fixed in https://github.com/wetware/ww/commit/156b4a59e562fd5d720394e173f5a14ae3fb1d60.
